config:
  dashboard:
    altitude: '+0'
    font:
      size: 10
    color:
      background: "#00AAFF"
      lit: "#FF7700"
      unlit: "#000000"
      mask: "#555555"
    launch_ycam:
      label: "カメラドライバ"
      package: rovi
      file: ycam3sxga_m.launch
      confirm: True
    launch_setup:
      label: "設定"
      package: rovi_qc
      file: setup01.launch
    launch_viewer:
      label: "Viewer"
      package: rovi_qc
      file: view01.launch
    launch_maxrate:
      label: "最大パフォーマンス(Floats)"
      package: rovi_qc
      file: maxrate.py
    launch_maxB64:
      label: "最大パフォーマンス(Base64)"
      package: rovi_qc
      file: maxB64.py
    indicator_rovi:
      label: "YCAM"
      topic: /rovi/stat
      type: std_msgs/Bool
      timeout: 2
